package com.github.starhq.template.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.io.Serializable;

/**
 * Base entity class providing a standardized primary key field for all persistent entities.
 * <p>
 * This class serves as the root of the entity inheritance hierarchy, ensuring consistent
 * primary key definition across all domain objects. By centralizing the {@code id} field
 * here, subclasses avoid redundant declarations and benefit from unified ID generation
 * strategy configuration.
 * <p>
 * <strong>Primary Key Strategy:</strong>
 * <p>
 * The {@code @TableId} annotation uses MyBatis-Plus default strategy ({@link IdType#ASSIGN_ID}),
 * which generates snowflake algorithm-based 64-bit unique IDs. This approach provides:
 * <ul>
 *     <li><strong>Global uniqueness</strong>: No coordination needed across database shards</li>
 *     <li><strong>Trend ordering</strong>: IDs are roughly time-sorted for efficient range queries</li>
 *     <li><strong>High performance</strong>: No database round-trip required for ID generation</li>
 * </ul>
 * <p>
 * <strong>Usage:</strong>
 * <pre>
 * {@code
 * @TableName("sys_user")
 * public class SysUser extends BaseIdEntity {
 *     private String username;
 *     private String email;
 *     // Additional fields...
 * }
 *
 * // Service layer usage
 * SysUser user = new SysUser();
 * user.setUsername("alice");
 * userService.save(user); // ID auto-generated by MP
 * Long userId = user.getId(); // Retrieve generated ID
 * }
 * </pre>
 *
 * @author wangjian
 * @author starhq (maintainer)
 * @version 1.0
 * @date 2026-03-24
 * @see com.baomidou.mybatisplus.annotation.TableId
 * @see com.baomidou.mybatisplus.annotation.IdType
 * @see <a href="https://baomidou.com/pages/223848/">MyBatis-Plus ID Generation Guide</a>
 */
@Data
public class BaseIdEntity {

    /**
     * The unique identifier for this entity instance.
     * <p>
     * This field is mapped to the primary key column of the corresponding database table
     * via {@link TableId}. By default, MyBatis-Plus uses {@link IdType#ASSIGN_ID} strategy,
     * which generates snowflake algorithm-based 64-bit numeric IDs before insertion.
     * <p>
     * <strong>Technical Details:</strong>
     * <ul>
     *     <li>Type: {@link Long} — 64-bit signed integer, compatible with snowflake IDs</li>
     *     <li>Nullability: {@code null} before persistence, non-{@code null} after {@code save()}</li>
     *     <li>Generation: Auto-generated by MyBatis-Plus {@code MetaObjectHandler} on INSERT</li>
     *     <li>Immutability: Should not be manually modified after entity persistence</li>
     * </ul>
     * <p>
     * <strong>Configuration Options:</strong>
     * <p>
     * If a different ID generation strategy is required, override the annotation in subclass:
     * <pre>
     * {@code
     * // Use database auto-increment
     * @TableId(type = IdType.AUTO)
     * private Long id;
     *
     * // Use UUID string (requires field type change to String)
     * @TableId(type = IdType.ASSIGN_UUID)
     * private String id;
     *
     * // Use application-assigned ID (e.g., from external system)
     * @TableId(type = IdType.INPUT)
     * private Long id;
     * }
     * </pre>
     * <p>
     * <strong>Query Tips:</strong>
     * <ul>
     *     <li>Fetch by ID: {@code baseMapper.selectById(id)} — uses primary key index</li>
     *     <li>Batch fetch: {@code baseMapper.selectBatchIds(Arrays.asList(id1, id2))}</li>
     *     <li>Range query: {@code WHERE id BETWEEN ? AND ?} — efficient due to snowflake ordering</li>
     * </ul>
     * <p>
     * <strong>Best Practices:</strong>
     * <ul>
     *     <li>Never expose raw IDs in public APIs without authorization checks</li>
     *     <li>Use {@code Optional<Long>} in method signatures to explicitly handle nullable IDs</li>
     *     <li>For sharded databases, ensure snowflake worker IDs are properly configured per instance</li>
     * </ul>
     *
     * @see TableId
     * @see IdType
     * @see com.baomidou.mybatisplus.core.mapper.BaseMapper#selectById(Serializable)
     */
    @TableId
    private Long id;

}